image: node:20

pipelines:
  branches:
    develop:
      - step:
          name: Test, Build & Deploy (dev)
          caches: [node]
          script:
            - npm ci
            - npm test
            - npm run build
            - printf '%s' "$GOOGLE_APPLICATION_CREDENTIALS_JSON" > firebase-key.json
            - export GOOGLE_APPLICATION_CREDENTIALS="$PWD/firebase-key.json"
            - npm install -g firebase-tools
            - firebase deploy --only hosting:dev --non-interactive

    main:
      - step:
          name: Test, Build & Deploy (prod)
          caches: [node]
          script:
            - npm ci
            - npm test
            - npm run build
            - printf '%s' "$GOOGLE_APPLICATION_CREDENTIALS_JSON" > firebase-key.json
            - export GOOGLE_APPLICATION_CREDENTIALS="$PWD/firebase-key.json"
            - npm install -g firebase-tools
            - firebase deploy --only hosting:prod --non-interactive
